Assistant checkpoint: Update supertest import in tests
Assistant generated file changes:
- src/tests/api.test.ts: Fix supertest import

---

User prompt:

~/PortfolioPage$ npm test

> portfoliopage@0.0.0 test
> node --experimental-vm-modules node_modules/jest/bin/jest.js

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  src/tests/api.test.ts
  ● Test suite failed to run

    src/tests/api.test.ts:2:8 - error TS1259: Module '"/home/runner/PortfolioPage/node_modules/@types/supertest/index"' can only be default-imported using the 'esModuleInterop' flag

    2 import request from 'supertest';
             ~~~~~~~

      node_modules/@types/supertest/index.d.ts:38:1
        38 export = supertest;
           ~~~~~~~~~~~~~~~~~~~
        This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.868 s
Ran all test suites.
 Environment updated. Reloading shell...
~/PortfolioPage$

Explain the error and try to find a different solution